server:

  port: 9090
  servlet:
    context-path: /practice
  #✅Improves performance by reducing response payload size.
  #✅ Faster load times for web pages and APIs.
  #✅ Saves bandwidth, especially for large JSON or HTML responses.
  compression:
    enabled: true # Turns on Gzip compression
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json
    min-response-size: 1024 # Compress responses only if they are larger than 1KB.
spring:
  devtools:
    livereload: # Enable live reload in browser HTML, CSS, JS changes
      enabled: true
    restart: # Enable automatic restart (default is true), Code Changes (Java files), application.properties
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/practice
    username: postgres
    password: anand@123
    driver-class-name: org.postgresql.Driver
  jpa:
    #The dialect tells Hibernate how to generate SQL optimized for PostgreSQL.
    #Ensures Hibernate generates PostgreSQL-specific SQL queries and Enables support for PostgreSQL data types and syntax.
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create  #Controls how Hibernate handles database schema updates.
    show-sql: true  #Enables logging of SQL statements executed by Hibernate. Prints all SQL queries in the console/logs.

